# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: Build-BancaMovil-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: npm ci
    displayName: 'Instalar dependencias'

  - script: npm run test
    displayName: 'Ejecutar pruebas'

  - script: npm run build
    displayName: 'Ejecutar build'
